#+STARTUP: content
#+AUTHOR: Rodrigo Leite
#+HUGO_BASE_DIR: ./
#+HUGO_SECTION: ./
#+HUGO_AUTO_SET_LASTMOD: t

* Pages
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
:EXPORT_HUGO_MENU: :menu main
:EXPORT_HUGO_SECTION: pages
:EXPORT_HUGO_WEIGHT: auto
:END:

** Test Page
:PROPERTIES:
:EXPORT_FILE_NAME: test-page
:END:

Hello! Lorem ipsum!


* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:
** Topic :@topic:
*** DONE Post Title :post:tags:
CLOSED: [2017-12-19 Tue 17:00]
:PROPERTIES:
:EXPORT_DATE: 2017-12-19
:EXPORT_FILE_NAME: post-title-in-slug-form
:END:



Kitten is playing with dead mouse murr i hate humans they are so annoying, for ptracy, but stand with legs in litter box, but poop outside cough furball into food bowl then scratch owner for a new one but tuxedo cats always looking dapper for stand in front of the computer screen. Please stop looking at your phone and pet me drink water out of the faucet. Cats secretly make all the worlds muffins lies down . Eat half my food and ask for more ccccccccccccaaaaaaaaaaaaaaatttttttttttttttttssssssssssssssss for morning beauty routine of licking self. Cats are cute. Attack like a vicious monster love and coo around boyfriend who purrs and makes the perfect moonlight eyes so i can purr and swat the glittery gleaming yarn to him (the yarn is from a $125 sweater) nyan fluffness ahh cucumber! i’m so hungry i’m so hungry but ew not for that , yet go into a room to decide you didn't want to be in there anyway. Rub whiskers on bare skin act innocent cough furball into food bowl then scratch owner for a new one but cat mojo cats secretly make all the worlds muffins stare at ceiling, for find empty spot in cupboard and sleep all day yet demand to be let outside at once, and expect owner to wait for me as i think about it. Meow pretend not to be evil so woops poop hanging from butt must get rid run run around house drag poop on floor maybe it comes off woops left brown marks on floor human slave clean lick butt now.

#+BEGIN_SRC bash -l 7 :hl_lines 8
echo 'Some source code content'
echo 'This line will be highlighted'
echo "This one won't"
#+END_SRC

**** Post Sub-Heading
This is another section within the post.
