baseurl = "https://leite.dev"
languageCode = "en-us"
theme = "terminal"
paginate = 5
disqusShortname = "Sky"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[markup.goldmark.renderer]
  unsafe= true

[languages]
  [languages.en]
    title = "Sky Leite"
    subtitle = ""
    keywords = "tech"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Sky Leite"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact Me"
        url = "mailto:sky@leite.dev"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/SkyLeite"
